### ISSUE TITLE
Feature: User can create a recipe entry

### ISSUE THREAD

**Issue by jghil** [jghil/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an entry for a recipe they've cooked. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to open a recipe form, fill in information about the recipe, upload a file for their finished dish, and save their recipe.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="148" alt="image" src="https://user-images.githubusercontent.com/103128961/190833494-d2f2dc64-b360-4b48-a9c1-7786e11b82b4.png">
<img width="524" alt="image" src="https://user-images.githubusercontent.com/103128961/190833531-ad29131c-17c7-4e8a-bdde-a946ce0049a4.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create and store user inputted data for the recipes.
- [x] Update `data.sql` to present values to database that can be manipulated in testing

### ☁️ Server Tasks

- [x] Update `server/index.js` to save user inputted data to the database using the post method.
   - [x] If not, respond with the correct error status code and a JSON error response
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a page with a form for a new recipe
     - [x] Require all fields to be required.
- [x] Listen for 'submit' events on recipe form and:
     - [x] save the form's input values into a new object and store it into a database
- [x] Make sure all input values are validated
- [x] Store code into database

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by jghil** [comment]
Gifs on slack
